theme: jekyll-theme-cayman
title: DuckMasterAl
author: DuckMasterAl#0001
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the DuckMasterAl Website | Made by DuckMasterAl

# social links
youtube_username:  DuckMasterAl RULES!!
